# Generated by Django 6.1 on 2026-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('location_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('record_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('location_id', models.CharField(db_index=True, max_length=64)),
                ('event_date_raw', models.CharField(blank=True, default='', max_length=64)),
                ('category_code', models.CharField(blank=True, default='', max_length=64)),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
                ('base_value_raw', models.CharField(blank=True, default='', max_length=64)),
                ('adjustment_raw', models.CharField(blank=True, default='', max_length=64)),
                ('total_value_raw', models.CharField(blank=True, default='', max_length=64)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('base_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('parse_issues', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['record_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('entry_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('record_ref_raw', models.CharField(blank=True, default='', max_length=128)),
                ('record_id_normalized', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('location_id', models.CharField(db_index=True, max_length=64)),
                ('recorded_on_raw', models.CharField(blank=True, default='', max_length=64)),
                ('value_raw', models.CharField(blank=True, default='', max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('parse_issues', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'system b entries',
                'ordering': ['entry_id'],
            },
        ),
    ]
