# Generated by Django 6.1 on 2026-08-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(db_index=True, max_length=64)),
                ('line_number', models.PositiveIntegerField()),
                ('natural_key', models.CharField(blank=True, default='', max_length=128)),
                ('reason', models.CharField(choices=[('DUPLICATE_SOURCE_KEY', 'Duplicate natural key within the same file'), ('BLANK_PRIMARY_KEY', 'Natural key was blank')], max_length=32)),
                ('raw_row', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'import anomalies',
                'ordering': ['source_file', 'line_number'],
            },
        ),
    ]
